### ISSUE TITLE
Images Not Loading In Project

### ISSUE THREAD

**Issue by kiwivi21** [artofpilgrim/portfolio-template#3]
Images are working perfectly fine in the home page, but as soon as you load a project none of them load. This is the case for linked images, embedded from file and more. This even goes to the point where the profile picture doesn't work which sucks as it doesn't make sense why these work in the home as opposed to the project.

**Comment by jelrad11** [comment]
hi kiwivi, i've not had that problem. Im not sure what you mean by home/project, but my websites been live for a few months without a problem. :) Maybe you could further elaborate on the issue?

**Comment by kiwivi21** [comment]
> hi kiwivi, i've not had that problem. Im not sure what you mean by home/project, but my websites been live for a few months without a problem. :) Maybe you could further elaborate on the issue?

Sorry for the late reply, https://youtu.be/RYwPLATmyrU in this video I show the issues that I am running into. I have everything linked the same as I am doing for the home page, but whenever I go into the project everything doesn't work even though the links and images work fine

**Comment by jelrad11** [comment]
Its because you are using relative paths compared to absolute. :)
add a slash to all your paths and it should fix the problem eg.:
/Resources/Renders/Jugrender.png 

Heres a resource on that: https://www.w3schools.com/html/html_filepaths.asp
There were somethings that might cause you trouble down the line: 
- Try to avoid spaces in file names 
- Consider file size, dont use png unless neccesary. check the load time per file your browser

good luck! :)

**Comment by kiwivi21** [comment]
> Its because you are using relative paths compared to absolute. :) add a slash to all your paths and it should fix the problem eg.: /Resources/Renders/Jugrender.png
> 
> Heres a resource on that: https://www.w3schools.com/html/html_filepaths.asp There were somethings that might cause you trouble down the line:
> 
> * Try to avoid spaces in file names
> * Consider file size, dont use png unless neccesary. check the load time per file your browser
> 
> good luck! :)

Hello, I really appreciate your response, good point on pngs I should switch them over to jpgs or similar. Avoiding spaces seems to have been one of if not the big issue so thank you. https://youtu.be/O_liitn14vg I am however still getting issues within the projects which is odd, that did fix the profile picture however so definitely on the right path

**Comment by jelrad11** [comment]
Maybe you could try moving the folder with the renders into the project folder? That works for me

![Image](https://github.com/user-attachments/assets/97c1a7d3-2f4d-419c-b19a-51f72eea7351)

**Comment by kiwivi21** [comment]
> renders into the project folder? That works fo

in trying I seem to still be getting the same issue unfortunately

**Comment by kiwivi21** [comment]
> > renders into the project folder? That works fo
> 
> in trying I seem to still be getting the same issue unfortunately

With some more testing, I am now able to get embedded images from other websites e.g. artstation, but ones being linked from within the project are simply not working. I have tried different images and stuff so must be something with the method that it links images from the project

**Comment by jelrad11** [comment]
Could it be an issue with your local server viewer? Maybe you could push it to live and see if the issue persists? If you have the same layer structure as i do there should be no problems

**Comment by kiwivi21** [comment]
> Could it be an issue with your local server viewer? Maybe you could push it to live and see if the issue persists? If you have the same layer structure as i do there should be no problems

https://kiwivi21.github.io/Projects/Jug/Jug.html hmmm not that either unfortunately (the images that are working are random ones linked from artstation)

**Comment by kiwivi21** [comment]
> Could it be an issue with your local server viewer? Maybe you could push it to live and see if the issue persists? If you have the same layer structure as i do there should be no problems

https://youtu.be/tmdGSWozV9E I believe I have found the issue for as to what is causing the images to not load. When inspecting the page I have noticed it is added /projects/jug/ before all the images even though I didnt add that code into the media section. Is there something that you did to remove that/how would I go about fixing that

Thank you

**Comment by kiwivi21** [comment]
I have found the issue and know how to fix it. Add the images to the folder and solely add the name of the file and not the file path. File path doesn't work for the projects and only works for the thumbnail. Hope this helps for anyone else who runs into this issue

![Image](https://github.com/user-attachments/assets/865652a2-39a7-456e-95c8-81165f28658f)
